# Generated by Django 3.0.8 on 2020-07-06 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_number', models.CharField(max_length=5)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Grid')),
            ],
        ),
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_destroy', models.BooleanField(default=False)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Party')),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShipType')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abs', models.IntegerField()),
                ('ord', models.IntegerField()),
                ('is_destroy', models.BooleanField(default=False)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ship')),
            ],
        ),
    ]
