# Generated by Django 3.0.8 on 2020-07-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='party_number',
            new_name='uuid',
        ),
    ]
